### ISSUE TITLE
Fix `MovieSearchView` preview

### ISSUE THREAD

**Issue by tillkruss** [tillkruss/ruddarr#15]
When previewing the `MovieSearchView` it should:

- [ ] Show the navigation tabs at the bottom
- [ ] Show the "Movies" back button to return to the `MoviesView`

**Comment by tillkruss** [comment]
@pteasima I don't know if this makes sense, or is a bad idea.

**Comment by pteasima** [comment]
Good idea in this particular case I think (the context is relevant to this preview). In most other cases, you should learn to work with the `pin preview` button and just work on a larger preview from another file. But here I understand how you want to be programmatically navigated to search, so I'll do that.

**Comment by tillkruss** [comment]
Done.
