### ISSUE TITLE
Implement API class; Show network errors in UI

### ISSUE THREAD

**Issue by tillkruss** [tillkruss/ruddarr#26]
[This guide](https://medium.com/mop-developers/build-your-first-swiftui-app-part-6-creating-the-api-helper-class-d73d589fc4b5) is good, just needs to use `async/await` instead?

This will help us capture network errors and authentication failures, or if the instance is down.

**Comment by tillkruss** [comment]
Good example too: https://github.com/dinotrnka/swiftui-blueprint/blob/part-6-api-helper-class/SwiftUIBlueprint/Code/Utilities/NetworkMonitor.swift

**Comment by pteasima** [comment]
@tillkruss be aware of related changes in #30, which simplify some of the needless generic classes etc.
