### ISSUE TITLE
Add dependency injection for AppStorage

### ISSUE THREAD

**Issue by pteasima** [tillkruss/ruddarr#31]
I want to control AppStorage so that I can default to having an Instance while developing. Having to create one through settings slows me down.

**Comment by tillkruss** [comment]
Good idea. I removed the sample here: 

https://github.com/tillkruss/ruddarr/blob/e0899ca0c45a9457d94c676ed329612897c1eedc/Ruddarr/Views/MovieSearchView.swift#L114

**Comment by pteasima** [comment]
I see instances have switched to some `@CloudStorage` wrapper, so we're no longer going with shared cloud AppStorage for that. I'll rebase this branch on top of the `MovieSort` stuff, so that we actually have a decent usage example.
