### ISSUE TITLE
Press "Movies" to get back to root view

### ISSUE THREAD

**Issue by tillkruss** [tillkruss/ruddarr#43]
When someone is deep in a nested navigation.

**Comment by pteasima** [comment]
Shame on Apple for not doing this by default. It works by default in UIKit. I have a SwiftUI solution, PR in a few min

**Comment by pteasima** [comment]
I can detect the tab being tapped while its already selected, but Im actually struggling to get the NavigationStack to respect the path binding at all. So it might take longer.

**Comment by pteasima** [comment]
my approach was working all along for popping from searchview. I was testing with popping movies but forgot to adjust those NavLinks 🤦‍♂️

we should be good now, PR soon.
